import random

REPLIES = [
    "Why is my account being suspended?",
    "I am scared. What should I do?",
    "How can I fix this?",
    "Where should I pay?",
    "Send me your UPI ID.",
    "Is this really from the bank?",
    "How long do I have to act?",
    "Can you explain properly?",
    "What will happen if I don't do this now?",
    "I am not very good with technology, please guide me.",
    "Is my money safe?",
    "Can you send me the payment details?",
    "Which bank is this from?",
    "I received many such messages before, is this genuine?",
    "Please tell me step by step.",
    "Can I talk to customer care?",
    "Why didn't I get any official email?",
    "What is the minimum amount I need to pay?",
    "Can you share your account number?",
    "Please give me the UPI ID again.",
    "I am very worried about losing my money.",
    "Are you sure this will fix the issue?",
    "What should I do after payment?",
    "Will I get confirmation message?",
    "Is this a one-time payment?",
    "Can you send the website link?",
    "Why is my account suddenly blocked?",
    "I just used my account yesterday.",
    "Please help me quickly.",
    "Is there any other way to solve this?",
    "Can I pay later?",
    "What is the deadline?",
    "Please explain in simple words.",
    "Is this related to KYC?",
    "Do I need to share any OTP?",
    "What details do you need from me?",
    "Can you repeat the instructions?",
    "Which department are you from?",
    "Can you send ID proof?",
    "How do I know you are real?",
    "I am confused, please help.",
    "I don't want any problem with my bank.",
    "Can you stay online while I pay?",
    "Tell me the exact steps.",
    "Should I open any app?",
    "What is the link for payment?",
    "Please type slowly, I will follow.",
    "Is this happening to everyone?",
    "Why did I not get call from bank?",
    "Can you message me the details?",
    "I will arrange money now.",
    "Please don't block my account.",
    "Help me resolve this fast.",
    "What if payment fails?",
    "Can I use Google Pay?",
    "Can I use PhonePe?",
    "Can I use Paytm?",
    "Please confirm after I pay.",
    "What amount should I transfer?",
    "Is this refundable?",
    "Can you assure me?",
    "Please guide me carefully.",
    "I trust you, please help.",
    "I am ready to pay now."
]
def generate_reply():
    return random.choice(REPLIES)
